name: Print pull request context
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows - здесь можно увидеть все триггеры
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        # https://docs.github.com/en/actions/learn-github-actions/expressions#functions здесь можно глянуть экспрешены
        run: echo "${{ toJSON(github.event) }}"
