name: Build and Deploy
on: [push, workflow_dispatch]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          # name - получаем доступ к папке с build и называем ее как угодно
          name: my-artifact
          # path - указание папки build, в которую соберется проект
          path: build
  deploy:
    needs: build-project
    runs-on: ubuntu-lates
    steps:
      - name: Get built project
        # получаем доступ к нашей папке с билдом
        uses: actions/download-artifact@v3
        with:
          # my-artifact - потому что на 17 строчке мы так назвали папку с билдом
          name: my-artifact
