name: Deploy React App
on:
  push:
    branches:
      - "master"
      # не тригерить джобы если изменения были только в любых файлах папки [workflows]
    paths-ignore:
      - ".github/workflows/*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    # по дефолту джобы запускаются одновременно в 3 потока, и не зависят друг от друга. для того, чтобы создать зависимость есть команда needs
    # в needs мы указываем, что джоба lint зависит от джобы test, и явно говорим дождаться успешного выполнения test, а только потом выполнять lint
    needs: test
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint validation
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Fake deploy...
