name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Run lint validation
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Fake deploy...
